modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
# The modid of the mod
modId="trapexpansion" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Trap Expansion" #mandatory
authors="Lemons" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Trap Expansion Adds Some Vanilla Style Traps!
'''
[[dependencies.trapexpansion]]
    modId="lemonlib"
    mandatory=true
    versionRange="[1.3.1,)"
    ordering="NONE"
    side="BOTH"